// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Refleks360.Infrastructure.Persistence;

#nullable disable

namespace Refleks360.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CompDbContext))]
    [Migration("20260512190845_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Refleks360.Infrastructure.Persistence.Entities.IncomeTaxBracketEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(8,6)");

                    b.Property<int>("TaxYearId")
                        .HasColumnType("int");

                    b.Property<decimal>("UpperLimit")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TaxYearId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("IncomeTaxBrackets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderIndex = 0,
                            Rate = 0.15m,
                            TaxYearId = 2026,
                            UpperLimit = 190000m
                        },
                        new
                        {
                            Id = 2,
                            OrderIndex = 1,
                            Rate = 0.20m,
                            TaxYearId = 2026,
                            UpperLimit = 400000m
                        },
                        new
                        {
                            Id = 3,
                            OrderIndex = 2,
                            Rate = 0.27m,
                            TaxYearId = 2026,
                            UpperLimit = 1500000m
                        },
                        new
                        {
                            Id = 4,
                            OrderIndex = 3,
                            Rate = 0.35m,
                            TaxYearId = 2026,
                            UpperLimit = 5300000m
                        },
                        new
                        {
                            Id = 5,
                            OrderIndex = 4,
                            Rate = 0.40m,
                            TaxYearId = 2026,
                            UpperLimit = 9999999999999.99m
                        });
                });

            modelBuilder.Entity("Refleks360.Infrastructure.Persistence.Entities.MonthlyTaxPeriodEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EndMonth")
                        .HasColumnType("int");

                    b.Property<decimal>("GvExemptionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GvExemptionRate")
                        .HasColumnType("decimal(8,6)");

                    b.Property<decimal>("SgkBaseMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SgkBaseMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StampExemptionAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("StartMonth")
                        .HasColumnType("int");

                    b.Property<int>("TaxYearId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaxYearId", "StartMonth")
                        .IsUnique();

                    b.ToTable("MonthlyTaxPeriods", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndMonth = 1,
                            GvExemptionAmount = 28075.50m,
                            GvExemptionRate = 0.15m,
                            SgkBaseMax = 247725.000m,
                            SgkBaseMin = 33030.00m,
                            StampExemptionAmount = 250.6977m,
                            StartMonth = 1,
                            TaxYearId = 2026
                        },
                        new
                        {
                            Id = 2,
                            EndMonth = 2,
                            GvExemptionAmount = 28075.50m,
                            GvExemptionRate = 0.15m,
                            SgkBaseMax = 247725.000m,
                            SgkBaseMin = 33030.00m,
                            StampExemptionAmount = 250.6977m,
                            StartMonth = 2,
                            TaxYearId = 2026
                        },
                        new
                        {
                            Id = 3,
                            EndMonth = 3,
                            GvExemptionAmount = 28075.50m,
                            GvExemptionRate = 0.15m,
                            SgkBaseMax = 247725.000m,
                            SgkBaseMin = 33030.00m,
                            StampExemptionAmount = 250.6977m,
                            StartMonth = 3,
                            TaxYearId = 2026
                        },
                        new
                        {
                            Id = 4,
                            EndMonth = 4,
                            GvExemptionAmount = 28075.50m,
                            GvExemptionRate = 0.15m,
                            SgkBaseMax = 247725.000m,
                            SgkBaseMin = 33030.00m,
                            StampExemptionAmount = 250.6977m,
                            StartMonth = 4,
                            TaxYearId = 2026
                        },
                        new
                        {
                            Id = 5,
                            EndMonth = 5,
                            GvExemptionAmount = 28075.50m,
                            GvExemptionRate = 0.15m,
                            SgkBaseMax = 247725.000m,
                            SgkBaseMin = 33030.00m,
                            StampExemptionAmount = 250.6977m,
                            StartMonth = 5,
                            TaxYearId = 2026
                        },
                        new
                        {
                            Id = 6,
                            EndMonth = 6,
                            GvExemptionAmount = 28075.50m,
                            GvExemptionRate = 0.15m,
                            SgkBaseMax = 247725.000m,
                            SgkBaseMin = 33030.00m,
                            StampExemptionAmount = 250.6977m,
                            StartMonth = 6,
                            TaxYearId = 2026
                        },
                        new
                        {
                            Id = 7,
                            EndMonth = 7,
                            GvExemptionAmount = 28075.50m,
                            GvExemptionRate = 0.15m,
                            SgkBaseMax = 247725.000m,
                            SgkBaseMin = 33030.00m,
                            StampExemptionAmount = 250.6977m,
                            StartMonth = 7,
                            TaxYearId = 2026
                        },
                        new
                        {
                            Id = 8,
                            EndMonth = 8,
                            GvExemptionAmount = 28075.50m,
                            GvExemptionRate = 0.20m,
                            SgkBaseMax = 247725.000m,
                            SgkBaseMin = 33030.00m,
                            StampExemptionAmount = 250.6977m,
                            StartMonth = 8,
                            TaxYearId = 2026
                        },
                        new
                        {
                            Id = 9,
                            EndMonth = 9,
                            GvExemptionAmount = 28075.50m,
                            GvExemptionRate = 0.20m,
                            SgkBaseMax = 247725.000m,
                            SgkBaseMin = 33030.00m,
                            StampExemptionAmount = 250.6977m,
                            StartMonth = 9,
                            TaxYearId = 2026
                        },
                        new
                        {
                            Id = 10,
                            EndMonth = 10,
                            GvExemptionAmount = 28075.50m,
                            GvExemptionRate = 0.20m,
                            SgkBaseMax = 247725.000m,
                            SgkBaseMin = 33030.00m,
                            StampExemptionAmount = 250.6977m,
                            StartMonth = 10,
                            TaxYearId = 2026
                        },
                        new
                        {
                            Id = 11,
                            EndMonth = 11,
                            GvExemptionAmount = 28075.50m,
                            GvExemptionRate = 0.20m,
                            SgkBaseMax = 247725.000m,
                            SgkBaseMin = 33030.00m,
                            StampExemptionAmount = 250.6977m,
                            StartMonth = 11,
                            TaxYearId = 2026
                        },
                        new
                        {
                            Id = 12,
                            EndMonth = 12,
                            GvExemptionAmount = 28075.50m,
                            GvExemptionRate = 0.20m,
                            SgkBaseMax = 247725.000m,
                            SgkBaseMin = 33030.00m,
                            StampExemptionAmount = 250.6977m,
                            StartMonth = 12,
                            TaxYearId = 2026
                        });
                });

            modelBuilder.Entity("Refleks360.Infrastructure.Persistence.Entities.TaxYearEntity", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<bool>("ApplySgkEmployerDiscount")
                        .HasColumnType("bit");

                    b.Property<decimal>("SgkEmployeeRate")
                        .HasColumnType("decimal(8,6)");

                    b.Property<decimal>("SgkEmployerDiscountRate")
                        .HasColumnType("decimal(8,6)");

                    b.Property<decimal>("SgkEmployerRate")
                        .HasColumnType("decimal(8,6)");

                    b.Property<decimal>("StampTaxRate")
                        .HasColumnType("decimal(8,6)");

                    b.Property<decimal>("UnemploymentEmployeeRate")
                        .HasColumnType("decimal(8,6)");

                    b.Property<decimal>("UnemploymentEmployerRate")
                        .HasColumnType("decimal(8,6)");

                    b.HasKey("Year");

                    b.ToTable("TaxYears", (string)null);

                    b.HasData(
                        new
                        {
                            Year = 2026,
                            ApplySgkEmployerDiscount = false,
                            SgkEmployeeRate = 0.14m,
                            SgkEmployerDiscountRate = 0.05m,
                            SgkEmployerRate = 0.2075m,
                            StampTaxRate = 0.00759m,
                            UnemploymentEmployeeRate = 0.01m,
                            UnemploymentEmployerRate = 0.02m
                        });
                });

            modelBuilder.Entity("Refleks360.Infrastructure.Persistence.Entities.IncomeTaxBracketEntity", b =>
                {
                    b.HasOne("Refleks360.Infrastructure.Persistence.Entities.TaxYearEntity", "TaxYear")
                        .WithMany("IncomeTaxBrackets")
                        .HasForeignKey("TaxYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaxYear");
                });

            modelBuilder.Entity("Refleks360.Infrastructure.Persistence.Entities.MonthlyTaxPeriodEntity", b =>
                {
                    b.HasOne("Refleks360.Infrastructure.Persistence.Entities.TaxYearEntity", "TaxYear")
                        .WithMany("MonthlyPeriods")
                        .HasForeignKey("TaxYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaxYear");
                });

            modelBuilder.Entity("Refleks360.Infrastructure.Persistence.Entities.TaxYearEntity", b =>
                {
                    b.Navigation("IncomeTaxBrackets");

                    b.Navigation("MonthlyPeriods");
                });
#pragma warning restore 612, 618
        }
    }
}
