// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Refleks360.Infrastructure.Persistence;

#nullable disable

namespace Refleks360.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CompDbContext))]
    [Migration("20260512192557_AddIdentityAndAuditLog")]
    partial class AddIdentityAndAuditLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Refleks360.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Refleks360.Infrastructure.Persistence.Entities.AuditLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("EntityKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("EntityType", "EntityKey");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("Refleks360.Infrastructure.Persistence.Entities.IncomeTaxBracketEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(8,6)");

                    b.Property<int>("TaxYearId")
                        .HasColumnType("int");

                    b.Property<decimal>("UpperLimit")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TaxYearId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("IncomeTaxBrackets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderIndex = 0,
                            Rate = 0.15m,
                            TaxYearId = 2026,
                            UpperLimit = 190000m
                        },
                        new
                        {
                            Id = 2,
                            OrderIndex = 1,
                            Rate = 0.20m,
                            TaxYearId = 2026,
                            UpperLimit = 400000m
                        },
                        new
                        {
                            Id = 3,
                            OrderIndex = 2,
                            Rate = 0.27m,
                            TaxYearId = 2026,
                            UpperLimit = 1500000m
                        },
                        new
                        {
                            Id = 4,
                            OrderIndex = 3,
                            Rate = 0.35m,
                            TaxYearId = 2026,
                            UpperLimit = 5300000m
                        },
                        new
                        {
                            Id = 5,
                            OrderIndex = 4,
                            Rate = 0.40m,
                            TaxYearId = 2026,
                            UpperLimit = 9999999999999.99m
                        });
                });

            modelBuilder.Entity("Refleks360.Infrastructure.Persistence.Entities.MonthlyTaxPeriodEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EndMonth")
                        .HasColumnType("int");

                    b.Property<decimal>("GvExemptionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GvExemptionRate")
                        .HasColumnType("decimal(8,6)");

                    b.Property<decimal>("SgkBaseMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SgkBaseMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StampExemptionAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("StartMonth")
                        .HasColumnType("int");

                    b.Property<int>("TaxYearId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaxYearId", "StartMonth")
                        .IsUnique();

                    b.ToTable("MonthlyTaxPeriods", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndMonth = 1,
                            GvExemptionAmount = 28075.50m,
                            GvExemptionRate = 0.15m,
                            SgkBaseMax = 247725.000m,
                            SgkBaseMin = 33030.00m,
                            StampExemptionAmount = 250.6977m,
                            StartMonth = 1,
                            TaxYearId = 2026
                        },
                        new
                        {
                            Id = 2,
                            EndMonth = 2,
                            GvExemptionAmount = 28075.50m,
                            GvExemptionRate = 0.15m,
                            SgkBaseMax = 247725.000m,
                            SgkBaseMin = 33030.00m,
                            StampExemptionAmount = 250.6977m,
                            StartMonth = 2,
                            TaxYearId = 2026
                        },
                        new
                        {
                            Id = 3,
                            EndMonth = 3,
                            GvExemptionAmount = 28075.50m,
                            GvExemptionRate = 0.15m,
                            SgkBaseMax = 247725.000m,
                            SgkBaseMin = 33030.00m,
                            StampExemptionAmount = 250.6977m,
                            StartMonth = 3,
                            TaxYearId = 2026
                        },
                        new
                        {
                            Id = 4,
                            EndMonth = 4,
                            GvExemptionAmount = 28075.50m,
                            GvExemptionRate = 0.15m,
                            SgkBaseMax = 247725.000m,
                            SgkBaseMin = 33030.00m,
                            StampExemptionAmount = 250.6977m,
                            StartMonth = 4,
                            TaxYearId = 2026
                        },
                        new
                        {
                            Id = 5,
                            EndMonth = 5,
                            GvExemptionAmount = 28075.50m,
                            GvExemptionRate = 0.15m,
                            SgkBaseMax = 247725.000m,
                            SgkBaseMin = 33030.00m,
                            StampExemptionAmount = 250.6977m,
                            StartMonth = 5,
                            TaxYearId = 2026
                        },
                        new
                        {
                            Id = 6,
                            EndMonth = 6,
                            GvExemptionAmount = 28075.50m,
                            GvExemptionRate = 0.15m,
                            SgkBaseMax = 247725.000m,
                            SgkBaseMin = 33030.00m,
                            StampExemptionAmount = 250.6977m,
                            StartMonth = 6,
                            TaxYearId = 2026
                        },
                        new
                        {
                            Id = 7,
                            EndMonth = 7,
                            GvExemptionAmount = 28075.50m,
                            GvExemptionRate = 0.15m,
                            SgkBaseMax = 247725.000m,
                            SgkBaseMin = 33030.00m,
                            StampExemptionAmount = 250.6977m,
                            StartMonth = 7,
                            TaxYearId = 2026
                        },
                        new
                        {
                            Id = 8,
                            EndMonth = 8,
                            GvExemptionAmount = 28075.50m,
                            GvExemptionRate = 0.20m,
                            SgkBaseMax = 247725.000m,
                            SgkBaseMin = 33030.00m,
                            StampExemptionAmount = 250.6977m,
                            StartMonth = 8,
                            TaxYearId = 2026
                        },
                        new
                        {
                            Id = 9,
                            EndMonth = 9,
                            GvExemptionAmount = 28075.50m,
                            GvExemptionRate = 0.20m,
                            SgkBaseMax = 247725.000m,
                            SgkBaseMin = 33030.00m,
                            StampExemptionAmount = 250.6977m,
                            StartMonth = 9,
                            TaxYearId = 2026
                        },
                        new
                        {
                            Id = 10,
                            EndMonth = 10,
                            GvExemptionAmount = 28075.50m,
                            GvExemptionRate = 0.20m,
                            SgkBaseMax = 247725.000m,
                            SgkBaseMin = 33030.00m,
                            StampExemptionAmount = 250.6977m,
                            StartMonth = 10,
                            TaxYearId = 2026
                        },
                        new
                        {
                            Id = 11,
                            EndMonth = 11,
                            GvExemptionAmount = 28075.50m,
                            GvExemptionRate = 0.20m,
                            SgkBaseMax = 247725.000m,
                            SgkBaseMin = 33030.00m,
                            StampExemptionAmount = 250.6977m,
                            StartMonth = 11,
                            TaxYearId = 2026
                        },
                        new
                        {
                            Id = 12,
                            EndMonth = 12,
                            GvExemptionAmount = 28075.50m,
                            GvExemptionRate = 0.20m,
                            SgkBaseMax = 247725.000m,
                            SgkBaseMin = 33030.00m,
                            StampExemptionAmount = 250.6977m,
                            StartMonth = 12,
                            TaxYearId = 2026
                        });
                });

            modelBuilder.Entity("Refleks360.Infrastructure.Persistence.Entities.TaxYearEntity", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<bool>("ApplySgkEmployerDiscount")
                        .HasColumnType("bit");

                    b.Property<decimal>("SgkEmployeeRate")
                        .HasColumnType("decimal(8,6)");

                    b.Property<decimal>("SgkEmployerDiscountRate")
                        .HasColumnType("decimal(8,6)");

                    b.Property<decimal>("SgkEmployerRate")
                        .HasColumnType("decimal(8,6)");

                    b.Property<decimal>("StampTaxRate")
                        .HasColumnType("decimal(8,6)");

                    b.Property<decimal>("UnemploymentEmployeeRate")
                        .HasColumnType("decimal(8,6)");

                    b.Property<decimal>("UnemploymentEmployerRate")
                        .HasColumnType("decimal(8,6)");

                    b.HasKey("Year");

                    b.ToTable("TaxYears", (string)null);

                    b.HasData(
                        new
                        {
                            Year = 2026,
                            ApplySgkEmployerDiscount = false,
                            SgkEmployeeRate = 0.14m,
                            SgkEmployerDiscountRate = 0.05m,
                            SgkEmployerRate = 0.2075m,
                            StampTaxRate = 0.00759m,
                            UnemploymentEmployeeRate = 0.01m,
                            UnemploymentEmployerRate = 0.02m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Refleks360.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Refleks360.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Refleks360.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Refleks360.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Refleks360.Infrastructure.Persistence.Entities.IncomeTaxBracketEntity", b =>
                {
                    b.HasOne("Refleks360.Infrastructure.Persistence.Entities.TaxYearEntity", "TaxYear")
                        .WithMany("IncomeTaxBrackets")
                        .HasForeignKey("TaxYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaxYear");
                });

            modelBuilder.Entity("Refleks360.Infrastructure.Persistence.Entities.MonthlyTaxPeriodEntity", b =>
                {
                    b.HasOne("Refleks360.Infrastructure.Persistence.Entities.TaxYearEntity", "TaxYear")
                        .WithMany("MonthlyPeriods")
                        .HasForeignKey("TaxYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaxYear");
                });

            modelBuilder.Entity("Refleks360.Infrastructure.Persistence.Entities.TaxYearEntity", b =>
                {
                    b.Navigation("IncomeTaxBrackets");

                    b.Navigation("MonthlyPeriods");
                });
#pragma warning restore 612, 618
        }
    }
}
